### PR TITLE
Added new form components

### PR DESCRIPTION
**Pull request by Dalibor22x**

### CODE REVIEW

**Comment by cedeber** [comment]
You need to pull on the branch v1.1, which is the current develop

**Comment by Dalibor22x** [comment]
Oh I forgot…

**Comment by cedeber** [comment]
I already changed it but you also must to push on v1.1, master is kept for version upgrades only. (that's why it was blocked ;) )

You also need to keep the js code in its own scope.

**Comment by cedeber** [comment]
And please try to clean code as much as possible. Not too much empty lines, code styling (spaces around `=` on the ftl files for instance, etc.)

**Comment by pierresandrin-oi** [comment]
Does not work because fields are not recognized by form module anymore.

**Pull request closed without merging**
